Improved firewall, don't setup if no network.

diff --git a/config/includes.chroot/etc/init.d/polyprog-firewall b/config/includes.chroot/etc/init.d/polyprog-firewall
--- a/config/includes.chroot/etc/init.d/polyprog-firewall
+++ b/config/includes.chroot/etc/init.d/polyprog-firewall
@@ -20,12 +20,13 @@ wait_for_connectivity() {
     local n_tries=0
     while ! host polyprog.epfl.ch >/dev/null 2>&1 && [ "$n_tries" -lt 5 ]; do
         n_tries="$((ntries + 1))"
-        log_action_cont_msg " waiting"
+        log_action_cont_msg " waiting ($n_tries / 5)"
         sleep 2
     done
 
     [ "$n_tries" -lt 5 ]
     log_action_end_msg $?
+    return $?
 }
 
 setup_firewall() {
@@ -101,10 +102,15 @@ stop_firewall() {
 
 case "$1" in
   start)
-        wait_for_connectivity
-	log_action_begin_msg "Setting up PolyProg Firewall"
-        setup_firewall
-        log_action_end_msg $?
+        if wait_for_connectivity; then
+            log_action_begin_msg "Setting up PolyProg Firewall"
+            setup_firewall
+            log_action_end_msg $?
+        else
+            log_warning_msg "Cannot connect to the network. Not setting up PolyProg Firewall."
+            log_warning_msg "Please contact PolyProg staff."
+            exit 1
+        fi
 	;;
   stop)
 	log_action_begin_msg "Stopping PolyProg Firewall"
