Faster detection of connections

diff --git a/config/includes.chroot/etc/init.d/polyprog-firewall b/config/includes.chroot/etc/init.d/polyprog-firewall
--- a/config/includes.chroot/etc/init.d/polyprog-firewall
+++ b/config/includes.chroot/etc/init.d/polyprog-firewall
@@ -17,15 +17,21 @@ N=/etc/init.d/polyprog-firewall
 
 wait_for_connectivity() {
     log_action_begin_msg "Waiting for network connectivity"
-    local n_tries=0
-    while ! host polyprog.epfl.ch >/dev/null 2>&1 && [ "$n_tries" -lt 2 ]; do
+    local n_tries=1
+    local max_tries=3
+
+    # has_connectivity is a return value; zero if connection succeeds
+    ping -c1 polyprog.epfl.ch >/dev/null 2>&1
+    local has_connectivity=$?
+
+    while [ "$has_connectivity" -ne 0 ] && [ "$n_tries" -lt "$max_tries" ]; do
+        log_action_cont_msg " waiting ($n_tries / $max_tries)"
+        sleep 3
+        ping -c1 polyprog.epfl.ch >/dev/null 2>&1
+        has_connectivity=$?
         n_tries=$((n_tries + 1))
-        log_action_cont_msg " waiting ($n_tries / 3)"
-        sleep 2
     done
 
-    [ "$n_tries" -lt 2 ]
-    local has_connectivity=$?
     log_action_end_msg $has_connectivity
     return $has_connectivity
 }
diff --git a/config/includes.chroot/etc/init.d/polyprog-network b/config/includes.chroot/etc/init.d/polyprog-network
--- a/config/includes.chroot/etc/init.d/polyprog-network
+++ b/config/includes.chroot/etc/init.d/polyprog-network
@@ -6,8 +6,8 @@
 # Required-Stop:     $network $named
 # Default-Start:     S
 # Default-Stop:      
-# Short-Description: Connects to the network using 802.1x authentication
-# Description:       Connects to the network. Authenticates using 802.1x.
+# Short-Description: Connects to the network.
+# Description:       Connects to the network. Knows about EPFL configuration.
 ### END INIT INFO
 
 . /lib/lsb/init-functions
@@ -16,25 +16,31 @@ N=/etc/init.d/polyprog-network
 
 wait_for_connectivity() {
     log_action_begin_msg "Waiting for network connectivity"
-    local n_tries=0
-    while ! host polyprog.epfl.ch >/dev/null 2>&1 && [ "$n_tries" -lt 2 ]; do
+    local n_tries=1
+    local max_tries=3
+
+    # has_connectivity is a return value; zero if connection succeeds
+    ping -c1 polyprog.epfl.ch >/dev/null 2>&1
+    local has_connectivity=$?
+
+    while [ "$has_connectivity" -ne 0 ] && [ "$n_tries" -lt "$max_tries" ]; do
+        log_action_cont_msg " waiting ($n_tries / $max_tries)"
+        sleep 3
+        ping -c1 polyprog.epfl.ch >/dev/null 2>&1
+        has_connectivity=$?
         n_tries=$((n_tries + 1))
-        log_action_cont_msg " waiting ($n_tries / 3)"
-        sleep 2
     done
 
-    [ "$n_tries" -lt 2 ]
-    local has_connectivity=$?
     log_action_end_msg $has_connectivity
     return $has_connectivity
 }
 
 start_network() {
     if ! wait_for_connectivity; then
-        dhclient -r eth0
+        dhclient -r wlan0
         killall wpa_supplicant
 
-        wpa_supplicant -D wext -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -B
+        wpa_supplicant -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -B
         sleep 8
         dhclient wlan0
     else
@@ -43,7 +49,7 @@ start_network() {
 }
 
 stop_network() {
-    dhclient -r eth0
+    dhclient -r wlan0
     killall wpa_supplicant
 }
 
